[build-system]
requires = ["setuptools>=61", "wheel", "scikit-build", "cmake>=3.22", "ninja", "typing_extensions","nvidia-cuda-runtime-cu11"]
build-backend = "setuptools.build_meta"
[tool.setuptools_scm]
write_to = "lyceanem/_version.py"
[tool.scikit-build]
build-dir = "build"
